services:
  - type: web
    name: resume-maker-backend
    env: node
    region: oregon
    rootDir: BACKEND
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
