services:
  - type: web
    name: resume-maker-backend
    env: node
    region: oregon
    rootDir: BACKEND
    plan: free
    buildCommand: npm ci --legacy-peer-deps
    startCommand: npm start
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        scope: runtime
        value: "5000"
