services:
  - type: web
    name: resume-maker-backend
    env: node
    region: oregon
    rootDir: BACKEND
    plan: free
    buildCommand: npm ci --legacy-peer-deps
    startCommand: npm start
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: MONGODB_URI
        value: mongodb+srv://kotasirichandana7:chandana2082@resumemaker.myex2ke.mongodb.net/resumemaker
      - key: JWT_SECRET
        value: your-strong-random-secret-min-32-chars
